# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16kYBbU97ZqATkgFGLFHbLaFJY2Vyh1Ga
"""

from datetime import datetime

# Read the chat file
with open("/content/hostel_bois.txt", "r", encoding="utf-8") as file:
    lines = file.readlines()

messages = []
system_count = 0
media_count = 0
deleted_count = 0

for line in lines:
    line = line.strip()
    if line == "":
        continue

    # Skip continuation lines
    if len(line) < 8 or line[2] != "/" or line[5] != "/":
        continue

    try:
        timestamp, rest = line.split(" - ", 1)
        sender, message = rest.split(": ", 1)
    except ValueError:
        system_count += 1
        continue

    if message == "<Media omitted>":
        media_count += 1
    if message == "This message was deleted":
        deleted_count += 1

    try:
        dt_obj = datetime.strptime(timestamp, "%d/%m/%y, %H:%M")
    except ValueError:
        dt_obj = datetime.now()

    messages.append({
        "timestamp": timestamp,
        "datetime": dt_obj,
        "sender": sender,
        "message": message
    })

print("=" * 50)
print("            FEATURE 1: CHAT PARSER")
print("=" * 50)
print("Total Parsed Messages :", len(messages))
print("System Messages       :", system_count)
print("Media Messages        :", media_count)
print("Deleted Messages      :", deleted_count)

# --- Base Parser (Required) ---
from datetime import datetime
with open("/content/hostel_bois.txt", "r", encoding="utf-8") as f:
    messages = []
    for line in f:
        line = line.strip()
        if len(line) < 8 or line[2] != "/" or line[5] != "/": continue
        try:
            ts, r = line.split(" - ", 1)
            s, m = r.split(": ", 1)
            messages.append({"timestamp": ts, "sender": s, "message": m})
        except ValueError: continue
# ------------------------------

message_count = {}
for msg in messages:
    sender = msg["sender"]
    message_count[sender] = message_count.get(sender, 0) + 1

participants = list(message_count.keys())
total_messages = len(messages)
first_date = messages[0]["timestamp"].split(",")[0]
last_date = messages[-1]["timestamp"].split(",")[0]

sorted_messages = sorted(message_count.items(), key=lambda x: x[1], reverse=True)

print("=" * 50)
print("            FEATURE 2: GROUP OVERVIEW")
print("=" * 50)
print("Group Name      : Hostel Bois 4ever")
print("First Date      :", first_date)
print("Last Date       :", last_date)
print("Total Messages  :", total_messages)
print("Participants    :", len(participants))
print("\nMessages Per Person")
print("-" * 50)
for person, count in sorted_messages:
    percentage = (count / total_messages) * 100
    print(f"{person:<10} : {count:>4} ({percentage:.1f}%)")

# --- Base Parser (Required) ---
from datetime import datetime
with open("/content/hostel_bois.txt", "r", encoding="utf-8") as f:
    messages = []
    for line in f:
        line = line.strip()
        if len(line) < 8 or line[2] != "/" or line[5] != "/": continue
        try:
            ts, r = line.split(" - ", 1)
            s, m = r.split(": ", 1)
            messages.append({"timestamp": ts, "sender": s, "message": m})
        except ValueError: continue
# ------------------------------

message_count = {}
day_count = {}
hour_count = {}

for msg in messages:
    sender = msg["sender"]
    message_count[sender] = message_count.get(sender, 0) + 1

    date = msg["timestamp"].split(",")[0]
    day_count[date] = day_count.get(date, 0) + 1

    time = msg["timestamp"].split(",")[1].strip()
    hour = time.split(":")[0]
    hour_count[hour] = hour_count.get(hour, 0) + 1

most_active = max(message_count, key=message_count.get)
highest_messages = message_count[most_active]
active_day = max(day_count, key=day_count.get)
highest_day_messages = day_count[active_day]
active_hour = max(hour_count, key=hour_count.get)
highest_hour_messages = hour_count[active_hour]

print("=" * 50)
print("       FEATURE 3: ACTIVITY ANALYSIS")
print("=" * 50)
print("Most Active Participant :", most_active)
print("Messages Sent           :", highest_messages)
print("\nMost Active Day         :", active_day)
print("Messages                :", highest_day_messages)
print("\nMost Active Hour        :", active_hour + ":00")
print("Messages                :", highest_hour_messages)

import numpy as np

# --- Base Parser (Required) ---
from datetime import datetime
with open("/content/hostel_bois.txt", "r", encoding="utf-8") as f:
    messages = []
    for line in f:
        line = line.strip()
        if len(line) < 8 or line[2] != "/" or line[5] != "/": continue
        try:
            ts, r = line.split(" - ", 1)
            s, m = r.split(": ", 1)
            messages.append({"timestamp": ts, "sender": s, "message": m})
        except ValueError: continue
# ------------------------------

participants = list(set(msg["sender"] for msg in messages))
participant_index = {person: idx for idx, person in enumerate(participants)}
heatmap = np.zeros((len(participants), 24))

for msg in messages:
    person = msg["sender"]
    hour = int(msg["timestamp"].split(",")[1].strip().split(":")[0])
    heatmap[participant_index[person]][hour] += 1

print("=" * 60)
print("FEATURE 4: ACTIVITY HEATMAP (messages by hour)")
print("=" * 60)
display_hours = [0, 3, 6, 9, 12, 15, 18, 21]

print(" " * 10, end="")
for h in display_hours:
    print(f"{h:02}", end="  ")
print()

for i in range(len(participants)):
    print(f"{participants[i]:<8}", end=" ")
    max_value = np.max(heatmap[i])
    for h in display_hours:
        value = heatmap[i][h]
        if max_value == 0: symbol = "."
        else:
            ratio = value / max_value
            if ratio == 0: symbol = "."
            elif ratio <= 0.25: symbol = "░"
            elif ratio <= 0.50: symbol = "▒"
            else: symbol = "█"
        print(symbol, end="   ")
    print()

import string

# --- Base Parser (Required) ---
from datetime import datetime
with open("/content/hostel_bois.txt", "r", encoding="utf-8") as f:
    messages = []
    for line in f:
        line = line.strip()
        if len(line) < 8 or line[2] != "/" or line[5] != "/": continue
        try:
            ts, r = line.split(" - ", 1)
            s, m = r.split(": ", 1)
            messages.append({"timestamp": ts, "sender": s, "message": m})
        except ValueError: continue
# ------------------------------

word_count = {}
for msg in messages:
    clean_msg = msg["message"].lower().translate(str.maketrans("", "", string.punctuation))
    for word in clean_msg.split():
        if len(word) > 1:
            word_count[word] = word_count.get(word, 0) + 1

sorted_words = sorted(word_count.items(), key=lambda x: x[1], reverse=True)

print("=" * 60)
print("        FEATURE 5: THIS GROUP'S FAVOURITE WORDS")
print("=" * 60)
if sorted_words:
    max_count = sorted_words[0][1]
    for word, count in sorted_words[:10]:
        bar_length = max(1, int((count / max_count) * 20))
        print(f"{word:<10} {'█' * bar_length:<20} {count}")

from datetime import datetime

# --- Base Parser (Required) ---
with open("/content/hostel_bois.txt", "r", encoding="utf-8") as f:
    messages = []
    for line in f:
        line = line.strip()
        if len(line) < 8 or line[2] != "/" or line[5] != "/": continue
        try:
            ts, r = line.split(" - ", 1)
            s, m = r.split(": ", 1)
            dt = datetime.strptime(ts, "%d/%m/%y, %H:%M")
            messages.append({"datetime": dt, "sender": s, "message": m})
        except ValueError: continue
# ------------------------------

response_data = []
for i in range(1, len(messages)):
    prev, curr = messages[i - 1], messages[i]
    if prev["sender"] == curr["sender"]: continue

    minutes = (curr["datetime"] - prev["datetime"]).total_seconds() / 60
    if minutes >= 0:
        response_data.append({"sender": curr["sender"], "previous_sender": prev["sender"], "minutes": minutes})

fastest = min(response_data, key=lambda x: x["minutes"])
slowest = max(response_data, key=lambda x: x["minutes"])
total_minutes = sum(i["minutes"] for i in response_data)
average_minutes = total_minutes / len(response_data)

avg_hours, avg_minutes = int(average_minutes // 60), int(average_minutes % 60)
days = int(slowest["minutes"] // (24 * 60))
hours = int((slowest["minutes"] % (24 * 60)) // 60)
minutes = int(slowest["minutes"] % 60)

pair_count = {}
for item in response_data:
    pair = f"{item['previous_sender']} ↔ {item['sender']}"
    pair_count[pair] = pair_count.get(pair, 0) + 1
best_pair = max(pair_count, key=pair_count.get)

print("=" * 60)
print("              FEATURE 6: RESPONSE ANALYSIS")
print("=" * 60)
print(f"Fastest Replier      : {fastest['sender']} ({fastest['minutes']:.0f} min)")
print(f"Slowest Replier      : {slowest['sender']} ({slowest['minutes']:.0f} min)")
print(f"Average Response Time: {f'{avg_hours} hr {avg_minutes} min' if avg_hours > 0 else f'{avg_minutes} min'}")
print(f"Longest Silent Streak: {f'{days} days {hours} hours' if days > 0 else f'{hours} hours {minutes} min'}")
print(f"Most Responsive Pair : {best_pair}")

# --- Base Parser (Required) ---
from datetime import datetime
with open("/content/hostel_bois.txt", "r", encoding="utf-8") as f:
    messages = []
    for line in f:
        line = line.strip()
        if len(line) < 8 or line[2] != "/" or line[5] != "/": continue
        try:
            ts, r = line.split(" - ", 1)
            s, m = r.split(": ", 1)
            messages.append({"timestamp": ts, "sender": s, "message": m})
        except ValueError: continue
# ------------------------------

message_count = {}
for msg in messages:
    message_count[msg["sender"]] = message_count.get(msg["sender"], 0) + 1

max_messages = max(message_count.values())
min_messages = min(message_count.values())

print("=" * 60)
print("              FEATURE 7: PERSONALITY DETECTION")
print("=" * 60)

for person in message_count.keys():
    total = message_count[person]

    night_messages = sum(
        1 for msg in messages
        if msg["sender"] == person and 0 <= int(msg["timestamp"].split(",")[1].strip().split(":")[0]) < 6
    )
    long_messages = sum(1 for msg in messages if msg["sender"] == person and len(msg["message"].split()) >= 15)

    if total == max_messages: personality = "👑 Spam King"
    elif total == min_messages: personality = "👻 Ghost"
    elif night_messages >= 20: personality = "🌙 Night Owl"
    elif long_messages >= 20: personality = "📚 Story Teller"
    elif total >= 500: personality = "❤️ Caretaker"
    else: personality = "🎭 Drama Queen"

    print(f"{person:<12} -> {personality}")

import string
from datetime import datetime

# --- Base Parser (Required) ---
with open("/content/hostel_bois.txt", "r", encoding="utf-8") as f:
    messages = []
    for line in f:
        line = line.strip()
        if len(line) < 8 or line[2] != "/" or line[5] != "/": continue
        try:
            ts, r = line.split(" - ", 1)
            s, m = r.split(": ", 1)
            dt = datetime.strptime(ts, "%d/%m/%y, %H:%M")
            messages.append({"timestamp": ts, "datetime": dt, "sender": s, "message": m})
        except ValueError: continue
# ------------------------------

# Metrics Processing
message_count = {}
day_count = {}
hour_count = {}
word_count = {}
response_data = []

for idx, msg in enumerate(messages):
    s, ts, m = msg["sender"], msg["timestamp"], msg["message"]
    message_count[s] = message_count.get(s, 0) + 1

    d = ts.split(",")[0]
    day_count[d] = day_count.get(d, 0) + 1

    h = ts.split(",")[1].strip().split(":")[0]
    hour_count[h] = hour_count.get(h, 0) + 1

    cw = m.lower().translate(str.maketrans("", "", string.punctuation))
    for w in cw.split():
        if len(w) > 1: word_count[w] = word_count.get(w, 0) + 1

    if idx > 0 and messages[idx-1]["sender"] != s:
        diff = (msg["datetime"] - messages[idx-1]["datetime"]).total_seconds() / 60
        if diff >= 0:
            response_data.append({"sender": s, "previous_sender": messages[idx-1]["sender"], "minutes": diff})

# Formatting Computations
sorted_words = sorted(word_count.items(), key=lambda x: x[1], reverse=True)
fastest = min(response_data, key=lambda x: x["minutes"])
slowest = max(response_data, key=lambda x: x["minutes"])
avg_m = sum(i["minutes"] for i in response_data) / len(response_data)
best_p = max(set(f"{i['previous_sender']} ↔ {i['sender']}" for i in response_data), key=lambda x: sum(1 for r in response_data if f"{r['previous_sender']} ↔ {r['sender']}" == x))

print("=" * 70)
print("                    FEATURE 8: GROUP DNA REPORT")
print("=" * 70)
print(f"\n📊 GROUP OVERVIEW\n{'-'*70}")
print(f"Total Messages      : {len(messages)}")
print(f"Participants        : {list(message_count.keys())}")
print(f"First Date          : {messages[0]['timestamp'].split(',')[0]}")
print(f"Last Date           : {messages[-1]['timestamp'].split(',')[0]}")

print(f"\n🏆 MOST ACTIVE MEMBER\n{'-'*70}\n{max(message_count, key=message_count.get)} ({max(message_count.values())} messages)")
print(f"\n📅 MOST ACTIVE DAY\n{'-'*70}\n{max(day_count, key=day_count.get)} ({max(day_count.values())} messages)")
print(f"\n⏰ MOST ACTIVE HOUR\n{'-'*70}\n{max(hour_count, key=hour_count.get)}:00 ({max(hour_count.values())} messages)")

print(f"\n💬 TOP 10 WORDS\n{'-'*70}")
for w, c in sorted_words[:10]:
    print(f"{w:<12} {'█'*max(1, int((c/sorted_words[0][1])*20)):<20} {c}")

print(f"\n⚡ RESPONSE ANALYSIS\n{'-'*70}")
print(f"Fastest Replier     : {fastest['sender']} ({fastest['minutes']:.0f} min)")
print(f"Slowest Replier     : {slowest['sender']} ({slowest['minutes']:.0f} min)")
print(f"Average Response    : {int(avg_m//60)} hr {int(avg_m%60)} min" if avg_m >= 60 else f"Average Response    : {int(avg_m)} min")
print(f"Best Response Pair  : {best_p}")

print(f"\n🎭 PERSONALITY REPORT\n{'-'*70}")
for p in message_count.keys():
    tot = message_count[p]
    nm = sum(1 for msg in messages if msg["sender"] == p and 0 <= msg["datetime"].hour < 6)
    lm = sum(1 for msg in messages if msg["sender"] == p and len(msg["message"].split()) >= 15)

    if tot == max(message_count.values()): personality = "👑 Spam King"
    elif tot == min(message_count.values()): personality = "👻 Ghost"
    elif nm >= 20: personality = "🌙 Night Owl"
    elif lm >= 20: personality = "📚 Story Teller"
    elif tot >= 500: personality = "❤️ Caretaker"
    else: personality = "🎭 Drama Queen"
    print(f"{p:<12} {personality}")
print("\n" + "=" * 70 + "\n              END OF GROUP DNA REPORT\n" + "=" * 70)